# Generated by Django 5.2.8 on 2025-11-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_chatthread_escalation_level_complaint_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
