# Generated by Django 5.2.8 on 2025-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
