# Generated by Django 5.2.8 on 2025-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_isavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isAvailable',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
