# Generated by Django 5.2.8 on 2025-11-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required to order.'),
        ),
    ]
