# Generated by Django 5.2.8 on 2025-11-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='consumer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
