# Generated by Django 5.2.8 on 2025-11-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_supplier_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='delivery_options',
            field=models.CharField(choices=[('DELIVERY', 'Delivery Only'), ('PICKUP', 'Pickup Only'), ('BOTH', 'Delivery & Pickup')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='consumer',
            name='lead_time',
            field=models.PositiveIntegerField(default=1, help_text='Average days to fulfill an order'),
        ),
    ]
