# Generated by Django 5.2.8 on 2025-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_consumer_delivery_options_consumer_lead_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='delivery_options',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_options',
            field=models.CharField(choices=[('DELIVERY', 'Delivery Only'), ('PICKUP', 'Pickup Only'), ('BOTH', 'Delivery & Pickup')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time',
            field=models.PositiveIntegerField(default=1, help_text='Average days to fulfill an order'),
        ),
    ]
